- name: "Install Minecraft Server"
  hosts: all 
  vars:
    apt_packages_list:
      - "openjdk-19-jre-headless"
      - "screen"
      - "ufw"
      - "vim"

  tasks:
    - name: "install all needed packages using apt"
      ansible.builtin.import_role:
        name: "install_package_w_apt"
      vars:
        package: "{{ item }}"
      loop: "{{ apt_packages_list }}"
      when: ansible_facts.pkg_mgr == "apt"


        # TODO 
  #   - add public-key to authenticate as minecraft user or password.
  #   - also it needs to be generated first... (use ansible-vault for the private key file to be used here)
  #   - move all .sh files into server_scriptsfolder
  #   - update plugins with newest versions (buy mobdisguise)
  #   - add password to unzip in ansible-vault var file and refer to it to decrypt zip files
  