- name: "Install Minecraft Server"
  hosts: all 
  vars:
    apt_packages_list:
      - "openjdk-19-jre-headless"
      - "screen"
      - "ufw"
      - "vim"

  tasks:
    - name: "install all needed packages using apt"
      ansible.builtin.import_role:
        name: "install_package_w_apt"
      vars:
        package: "{{ item }}"
      loop: "{{ apt_packages_list }}"
      when: ansible_facts.pkg_mgr == "apt"

    

