- name: "Supported Minecraft servertypes"
  ansible.builtin.debug:
    msg: {{ item }}
  loop: supported_servertypes

- name: "Fail when passed type is not supported"
  ansible.builtin.fail:
    msg: "Your specified servertype: {{ type }} is not supported! Abborting..."
  when: type != item
  loop: supported_servertypes

- name: "Check and install apt requirements"
  ansible.builtin.import_tasks:
    file: "install_python_apt.yaml"

- name: "install needed packages for Mineraft Server using apt"
  ansible.builtin.apt:
    state: "present"
    name: "{{ item }}"
  become: true
  loop: "{{ apt_packages_list }}"
  when: ansible_facts.pkg_mgr == "apt"

- name: "Prepare the Mineraft Server environment"
  ansible.builtin.import_tasks:
    file: "prepare_server_environment.yaml"

- name: "Download Serverfile and install it"
  ansible.builtin.import_tasks:
    file: "download_serverfile.yaml"

